version: 2
jobs:
  libthemis:
    docker:
      - image: linuxbrew/brew:latest
    steps:
      - run:
          name: Check Homebrew installation
          command: |
            brew update
            brew --env
            brew config
            brew cleanup
      - checkout
      - run:
          name: brew tap cossacklabs/core
          command: |
            # Link the checked out working copy instead of actually tapping
            mkdir -p $(brew --repo)/Library/Taps/cossacklabs
            ln -s $PWD $(brew --repo)/Library/Taps/cossacklabs/homebrew-core
      - run: brew install libthemis
      - run: brew audit libthemis --verbose
      - run: brew test libthemis

workflows:
  version: 2
  formulae:
    jobs:
      - libthemis
